"""add ai feedback

Revision ID: 0db9aa31bbec
Revises: 5266b63a5e07
Create Date: 2026-05-08 23:09:05.220869

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0db9aa31bbec'
down_revision: Union[str, Sequence[str], None] = '5266b63a5e07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('conversation_id', sa.Integer(), nullable=True),
    sa.Column('message_index', sa.Integer(), nullable=True),
    sa.Column('question', sa.Text(), nullable=True),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('rating', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_feedback_conversation_id'), 'ai_feedback', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_ai_feedback_created_at'), 'ai_feedback', ['created_at'], unique=False)
    op.create_index(op.f('ix_ai_feedback_id'), 'ai_feedback', ['id'], unique=False)
    op.create_index(op.f('ix_ai_feedback_user_id'), 'ai_feedback', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_feedback_user_id'), table_name='ai_feedback')
    op.drop_index(op.f('ix_ai_feedback_id'), table_name='ai_feedback')
    op.drop_index(op.f('ix_ai_feedback_created_at'), table_name='ai_feedback')
    op.drop_index(op.f('ix_ai_feedback_conversation_id'), table_name='ai_feedback')
    op.drop_table('ai_feedback')
    # ### end Alembic commands ###
