"""add preferred lang

Revision ID: 46437df71aa0
Revises: 5f9e76d289ee
Create Date: 2026-05-08 21:35:45.600074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46437df71aa0'
down_revision: Union[str, Sequence[str], None] = '5f9e76d289ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('preferred_lang', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'preferred_lang')
    # ### end Alembic commands ###
