"""add analytics

Revision ID: 5f9e76d289ee
Revises: 8d5e245a37c2
Create Date: 2026-05-03 18:17:13.631751

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f9e76d289ee'
down_revision: Union[str, Sequence[str], None] = '8d5e245a37c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_query_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('lang', sa.String(length=10), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('docs_found', sa.Integer(), nullable=True),
    sa.Column('answered', sa.Boolean(), nullable=True),
    sa.Column('endpoint', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_query_logs_category'), 'ai_query_logs', ['category'], unique=False)
    op.create_index(op.f('ix_ai_query_logs_created_at'), 'ai_query_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_ai_query_logs_id'), 'ai_query_logs', ['id'], unique=False)
    op.create_index(op.f('ix_ai_query_logs_lang'), 'ai_query_logs', ['lang'], unique=False)
    op.create_index(op.f('ix_ai_query_logs_user_id'), 'ai_query_logs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_query_logs_user_id'), table_name='ai_query_logs')
    op.drop_index(op.f('ix_ai_query_logs_lang'), table_name='ai_query_logs')
    op.drop_index(op.f('ix_ai_query_logs_id'), table_name='ai_query_logs')
    op.drop_index(op.f('ix_ai_query_logs_created_at'), table_name='ai_query_logs')
    op.drop_index(op.f('ix_ai_query_logs_category'), table_name='ai_query_logs')
    op.drop_table('ai_query_logs')
    # ### end Alembic commands ###
