"""add procedures timeline

Revision ID: 6b40a7e177bf
Revises: 49c5e5d34ae2
Create Date: 2026-04-16 12:32:20.138661

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b40a7e177bf'
down_revision: Union[str, Sequence[str], None] = '49c5e5d34ae2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('procedure_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(), nullable=True),
    sa.Column('estimated_days', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_procedure_types_id'), 'procedure_types', ['id'], unique=False)
    op.create_table('procedure_steps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('procedure_type_id', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('documents_required', sa.Text(), nullable=True),
    sa.Column('estimated_days', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['procedure_type_id'], ['procedure_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_procedure_steps_id'), 'procedure_steps', ['id'], unique=False)
    op.create_table('user_procedures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('procedure_type_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['procedure_type_id'], ['procedure_types.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_procedures_id'), 'user_procedures', ['id'], unique=False)
    op.create_table('user_step_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_procedure_id', sa.Integer(), nullable=False),
    sa.Column('step_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'in_progress', 'completed', 'blocked', name='stepstatus'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['step_id'], ['procedure_steps.id'], ),
    sa.ForeignKeyConstraint(['user_procedure_id'], ['user_procedures.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_step_progress_id'), 'user_step_progress', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_step_progress_id'), table_name='user_step_progress')
    op.drop_table('user_step_progress')
    op.drop_index(op.f('ix_user_procedures_id'), table_name='user_procedures')
    op.drop_table('user_procedures')
    op.drop_index(op.f('ix_procedure_steps_id'), table_name='procedure_steps')
    op.drop_table('procedure_steps')
    op.drop_index(op.f('ix_procedure_types_id'), table_name='procedure_types')
    op.drop_table('procedure_types')
    # ### end Alembic commands ###
